### ISSUE TITLE
Cannot set property 'options' of undefined

### ISSUE THREAD

**Issue by sastrakhan** [nuxy/slot-machine-gen#3]
I'm getting an error saying `options` is undefined (probably because I'm not setting it); if it's required why does the [example code here](https://www.npmjs.com/package/react-slot-machine-gen) say it's not?

`<SlotMachine reels={reels} play={this.state.play} />
`

However the readme here says instantiation is as follows:
`const slotMachine = new SlotMachine(container, reels, callback, options);
`

What values do we put for container and options?  There aren't examples.  Thanks! 

p.s:  I'm trying to use this library with React

**Comment by nuxy** [comment]
@sastrakhan

The code example doesn't exactly reflect full capabilities of the React library. While this is something that is defined in the [component](https://github.com/nuxy/react-slot-machine-gen/blob/master/src/react-slot-machine.js#L48) it's clearly missing from the documentation.  My bad.   I have [addressed](https://github.com/nuxy/react-slot-machine-gen#component-props) in the latest release.

> I'm getting an error saying options is undefined 

This is something I have not experienced.  Out of curiosity, are you able to run the [demo](https://github.com/nuxy/react-slot-machine-gen/tree/master/demo) successfully?

**Comment by sastrakhan** [comment]
Thanks @nuxy for the update.  It could've been my ignorance of the README but I thought I could copy and paste the React example code as is (obviously not because there is no `../dist` folder).  I ended up having to create a file to make the SlotMachine component and then a different one that resembled the example in the README as seen [here](https://github.com/sastrakhan/weather-app/tree/main/src/slotmachine
).

I created a [PR](https://github.com/nuxy/react-slot-machine-gen/pull/3) for what I'd like the README to be.  No worries if you deny it.  Other more experienced devs may find this explanation elementary but I figured if I was confused, there may be other devs who have tried to use this library and then quit from confusion.  I wouldn't want that because I think what you made here is awesome!

**Comment by nuxy** [comment]
@sastrakhan 

>  It could've been my ignorance of the README but I thought I could copy and paste the React example code as is (obviously not because there is no ../dist folder).

The example was written in the context of the demo (i.e. the `dist` directory contains the Babel transpiled code).  However, in your case you should be able to `import` the original source using:

```javascript
import React       from 'react';
import SlotMachine from 'react-slot-machine-gen';
```

I will update the example to reflect this.
