### ISSUE TITLE
Can the game be won?

### ISSUE THREAD

**Issue by mattheweller** [nuxy/slot-machine-gen#4]
Unless I'm mistaken, the play function does not seem to have logic to support identifying a win. Is there an example implementation of that logic, or is this game for demonstrative purposes only? Thanks!

**Comment by nuxy** [comment]
Hi @mattheweller,

When creating a new `SlotMachine` instance you can pass a [callback argument that returns pay-line values](https://github.com/nuxy/slot-machine-gen/blob/master/src/slot-machine.js#L19) selected during a game session.  This allows you to write logic to show a simple message or something complex like an animation.

#### Example
```
var callback = function(v) {
  if (v[0].title === 'cherry' && v[1].title === 'cherry' && v[2].title === 'cherry') {
    window.alert("You're a winner!");
  }
};
```

Hope this helps.

**Comment by mattheweller** [comment]
Makes perfect sense. Thanks!

**Comment by nuxy** [comment]
Note the changes in my example, notably `v[index].title`

Sorry about that.  Was :zzz: when I replied.
