### ISSUE TITLE
server based rng

### ISSUE THREAD

**Issue by vip3r011** [nuxy/slot-machine-gen#6]
if u made this server based with example express to get reel data

crypto shuld be better than math random?
for example. dont know how biased this is

```
'use strict';
const crypto = require('crypto');

class RNG {
    static random() {
        try {
            const randomBytes = crypto.randomBytes(4);
            const float = (randomBytes.readUInt32LE(0) / 0xffffffff);
            return (float);
        }
        catch (err) {
            throw err;
        }
    }
}
```

**Comment by nuxy** [comment]
To answer your question which is _outside of what this package provides_.  Using Node's `crypto.randomBytes()` method is a far superior alternative to `Math.random` since it's seeded with entropy from `/dev/urandom`

Hope this helps.
